Update libs

diff --git a/bin/kube-nodeshell b/bin/kube-nodeshell
--- a/bin/kube-nodeshell
+++ b/bin/kube-nodeshell
@@ -1,6 +1,11 @@
-#!/usr/bin/env toolset
+#!/usr/bin/env bash
 # vi: ft=bash
-# shellcheck shell=bash
+# shellcheck shell=bash disable=SC1091,SC2310
+set -e -u -o pipefail
+
+## source toolset
+source toolset || exit 1
+
 
 function create_manifest {
     local nodename="${1:-""}"
@@ -72,7 +77,7 @@ function usage() {
     uses chroot to enter the nodes filesystem as if you were logged in on a node
     itself.
 
-    ${TOOLSET_SCRIPT_NAME} -n <namespace> -s <servername>
+    ${TOOLSET_SCRIPT_NAME:-${0}} -n <namespace> -s <servername>
 
     Arguments:
       --server,    -s - The name of the node to connect to.
@@ -82,7 +87,7 @@ function usage() {
       --podname,   -p - The pod name to use when starting (Default: k8s-nodeshell).
 
     Example:
-      ${TOOLSET_SCRIPT_NAME} -n default -s ip-10-30-65-200.eu-central-1.compute.internal
+      ${TOOLSET_SCRIPT_NAME:-${0}} -n default -s ip-10-30-65-200.eu-central-1.compute.internal
 
 EOF
 
@@ -103,7 +108,7 @@ function main {
     local fullpodname
 
     ## Parse command line arguments
-    while [ "${1:-""}" != "" ]
+    while [[ "${1:-""}" != "" ]]
     do
         case "${1}"
         in
@@ -123,6 +128,10 @@ function main {
                 podname="${2:-""}"
                 shift
 	        ;;
+            *)
+                log::error "Invalid input: ${1}"
+                exit 1
+            ;;
         esac
 
         shift || true
diff --git a/bin/kube-sshinject b/bin/kube-sshinject
--- a/bin/kube-sshinject
+++ b/bin/kube-sshinject
@@ -1,6 +1,10 @@
-#!/usr/bin/env toolset
+#!/usr/bin/env bash
 # vi: ft=bash
-# shellcheck shell=bash
+# shellcheck shell=bash disable=SC1091,SC2310
+set -e -u -o pipefail
+
+## source toolset
+source toolset || exit 1
 
 
 function create_manifest {
@@ -56,7 +60,7 @@ function usage() {
     This script mounts the authorized_keys file of a kubernetes node
     and adds an SSH key of choice to ensure SSH access on a node.
 
-    ${TOOLSET_SCRIPT_NAME} -n <namespace> -a <pubkey> -a /root/.ssh/authorized_keys
+    ${TOOLSET_SCRIPT_NAME:-${0}} -n <namespace> -a <pubkey> -a /root/.ssh/authorized_keys
 
     Arguments:
       --pubkey, -p    - The ssh public keyfile to inject
@@ -68,7 +72,7 @@ function usage() {
                         (Default: /root/.ssh/authorized_keys)
 
     Example:
-      ${TOOLSET_SCRIPT_NAME} -n default -a ~/.ssh/id_rsa
+      ${TOOLSET_SCRIPT_NAME:-${0}} -n default -a ~/.ssh/id_rsa
 
 EOF
 
@@ -88,9 +92,9 @@ function main {
     authfile=/root/.ssh/authorized_keys
 
     ## Parse command line arguments
-    while [ "${1:-""}" != "" ]
+    while [[ "${1:-""}" != "" ]]
     do
-        case "$1"
+        case "${1}"
         in
 	        -h|--help)
                 usage 0
@@ -108,6 +112,10 @@ function main {
                 authfile="${2:-""}"
                 shift
 	        ;;
+            *)
+                log::error "Invalid input: ${1}"
+                exit 1
+            ;;
         esac
 
         shift || true
diff --git a/bin/vimedit b/bin/vimedit
--- a/bin/vimedit
+++ b/bin/vimedit
@@ -1,6 +1,11 @@
-#!/usr/bin/env toolset
+#!/usr/bin/env bash
 # vi: ft=bash
-# shellcheck shell=bash
+# shellcheck shell=bash disable=SC1091
+set -e -u -o pipefail
+
+## source toolset
+source toolset || exit 1
+
 
 ## Print help output
 function usage {
@@ -12,7 +17,7 @@ function usage {
     as a file or as content in vim. It can be used for easy and quickly editting
     multiple files or put all output of a one liner in vim.
 
-    ${TOOLSET_SCRIPT_NAME} [-f|-c]
+    ${TOOLSET_SCRIPT_NAME:-${0}} [-f|-c]
 
    Arguments:
     -f, --file      - Read filenames from stdin and open in vim
@@ -21,8 +26,8 @@ function usage {
     -h, --help      - Show this menu
 
     Example:
-      \$( which somescript ) | ${TOOLSET_SCRIPT_NAME} -f
-      ps -ef | ${TOOLSET_SCRIPT_NAME} -c
+      \$( which somescript ) | ${TOOLSET_SCRIPT_NAME:-${0}} -f
+      ps -ef | ${TOOLSET_SCRIPT_NAME:-${0}} -c
 
 EOF
 
@@ -40,7 +45,7 @@ function existsfilter {
         fi
     done < /dev/stdin
 
-    printf "${files[*]}"
+    printf "%s\n" "${files[@]}"
 }
 
 
@@ -65,12 +70,19 @@ function main {
                 read_filename=1
                 shift
             ;;
+            *)
+                log::error "Invalid input: ${1}"
+                exit 1
+            ;;
         esac
 
         shift || true
     done
 
-    if ! var::eq "$( var::sum "${read_filename}" "${read_content}" )" 1
+    local optcount
+          optcount="$( var::sum "${read_filename}" "${read_content}" )"
+
+    if ! var::eq "${optcount}" 1
     then
         log::warning "Use either --content or --file"
         usage
diff --git a/bin/wait-until b/bin/wait-until
--- a/bin/wait-until
+++ b/bin/wait-until
@@ -1,6 +1,11 @@
-#!/usr/bin/env toolset
+#!/usr/bin/env bash
 # vi: ft=bash
-# shellcheck shell=bash
+# shellcheck shell=bash disable=SC1091
+set -e -u -o pipefail
+
+## source toolset
+source toolset || exit 1
+
 
 ## Print help output
 function usage {
@@ -11,7 +16,7 @@ function usage {
     This script waits in a loop until a given condition is met.
     It can be used in scripts to wait and perform a successive action when done.
 
-    ${TOOLSET_SCRIPT_NAME}  --run <command condition> [--sleep <seconds>|--tries <int>|--exitcode <int>]
+    ${TOOLSET_SCRIPT_NAME:-${0}}  --run <command condition> [--sleep <seconds>|--tries <int>|--exitcode <int>]
 
 
     Required arguments:
@@ -29,7 +34,7 @@ function usage {
       1 if condition is not met after N retries
 
     Example:
-      ${TOOLSET_SCRIPT_NAME} --run 'ps -ef | grep -v grep | grep -q kubelet' --tries 5 --sleep 1 --exitcode 1
+      ${TOOLSET_SCRIPT_NAME:-${0}} --run 'ps -ef | grep -v grep | grep -q kubelet' --tries 5 --sleep 1 --exitcode 1
 
 EOF
 
@@ -66,6 +71,10 @@ function main {
             ;;
             -v|--verbose)
                 verbose=1
+            ;;
+            *)
+                log::error "Invalid input: ${1}"
+                exit 1
             ;;
         esac
         shift
